services:

  app-1:
    build: .
    image: poc-app:latest
    container_name: app-1
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_REDIS_PASSWORD=Serhat1234.
      - SPRING_PROFILES_ACTIVE=external
      - SPRING_DATA_REDIS_SENTINEL_MASTER=mymaster
      - SPRING_DATA_REDIS_SENTINEL_NODES=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
    depends_on:
      redis-master:
        condition: service_healthy
      redis-sentinel-1:
        condition: service_started
      redis-sentinel-2:
        condition: service_started
      redis-sentinel-3:
        condition: service_started
      hazelcast-1:
        condition: service_started
      hazelcast-2:
        condition: service_started
      hazelcast-3:
        condition: service_started
    networks:
      - hazelcast-net 

  app-2:
    container_name: app-2
    image: poc-app:latest

    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_REDIS_PASSWORD=Serhat1234.
      - SPRING_PROFILES_ACTIVE=external
      - SPRING_DATA_REDIS_SENTINEL_MASTER=mymaster
      - SPRING_DATA_REDIS_SENTINEL_NODES=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
    depends_on:
      redis-master:
        condition: service_healthy
      redis-sentinel-1:
        condition: service_started
      redis-sentinel-2:
        condition: service_started
      redis-sentinel-3:
        condition: service_started
      hazelcast-1:
        condition: service_started
      hazelcast-2:
        condition: service_started
      hazelcast-3:
        condition: service_started
    networks:
      - hazelcast-net 

  app-3:
    container_name: app-3
    image: poc-app:latest

    ports:
      - "8083:8080"
    environment:
      - SPRING_DATA_REDIS_PASSWORD=Serhat1234.
      - SPRING_PROFILES_ACTIVE=external
      - SPRING_DATA_REDIS_SENTINEL_MASTER=mymaster
      - SPRING_DATA_REDIS_SENTINEL_NODES=redis-sentinel-1:26379,redis-sentinel-2:26379,redis-sentinel-3:26379
    depends_on:
      redis-master:
        condition: service_healthy
      redis-sentinel-1:
        condition: service_started
      redis-sentinel-2:
        condition: service_started
      redis-sentinel-3:
        condition: service_started
      hazelcast-1:
        condition: service_started
      hazelcast-2:
        condition: service_started
      hazelcast-3:
        condition: service_started
    networks:
      - hazelcast-net 

  hazelcast-1:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast-1
    ports:
      - "5701:5701"
    environment:

      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_MULTICAST_ENABLED=false
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701


    networks:
      - hazelcast-net 

  hazelcast-2:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast-2
    ports:
      - "5702:5701"
    environment:
      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_MULTICAST_ENABLED=false
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701
    networks:
      - hazelcast-net 

  hazelcast-3:
    image: hazelcast/hazelcast:5.3
    container_name: hazelcast-3
    ports:
      - "5703:5701"
    environment:
      - HZ_CLUSTERNAME=dev
      - HZ_NETWORK_JOIN_TCPIP_ENABLED=true
      - HZ_NETWORK_JOIN_MULTICAST_ENABLED=false
      - HZ_NETWORK_JOIN_TCPIP_MEMBERS=hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701
    networks:
      - hazelcast-net 

  redis-master:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass Serhat1234.
    networks:
      hazelcast-net:
        aliases:
          - redis-master
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Serhat1234.", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-slave-1:
    image: redis:7
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --slaveof redis-master 6379 --masterauth Serhat1234. --requirepass Serhat1234.
    depends_on:
      - redis-master
    networks:
      - hazelcast-net 

  redis-slave-2:
    image: redis:7
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes --slaveof redis-master 6379 --masterauth Serhat1234. --requirepass Serhat1234.
    depends_on:
      - redis-master
    networks:
      - hazelcast-net 

  redis-sentinel-1:
    image: redis:7
    container_name: redis-sentinel-1
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    command: >
      sh -c "mkdir -p /tmp/redis &&
      echo 'port 26379' > /tmp/redis/sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel auth-pass mymaster Serhat1234.' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> /tmp/redis/sentinel.conf &&
      redis-server /tmp/redis/sentinel.conf --sentinel"

    ports:
      - "26379:26379"
    networks:
      - hazelcast-net 

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"

  grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
          - "3000:3000"
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=serhat21 # Giriş şifresi
        depends_on:
          - prometheus

  redis-sentinel-2:
    image: redis:7
    container_name: redis-sentinel-2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    command: >
      sh -c "mkdir -p /tmp/redis &&
      echo 'port 26379' > /tmp/redis/sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel auth-pass mymaster Serhat1234.' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> /tmp/redis/sentinel.conf &&
      redis-server /tmp/redis/sentinel.conf --sentinel"

    ports:
      - "26380:26379"
    networks:
      - hazelcast-net 

  redis-sentinel-3:
    image: redis:7
    container_name: redis-sentinel-3
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    command: >
      sh -c "mkdir -p /tmp/redis &&
      echo 'port 26379' > /tmp/redis/sentinel.conf &&
      echo 'sentinel resolve-hostnames yes' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel auth-pass mymaster Serhat1234.' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 10000' >> /tmp/redis/sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> /tmp/redis/sentinel.conf &&
      redis-server /tmp/redis/sentinel.conf --sentinel"

    ports:
      - "26381:26379"
    networks:
      - hazelcast-net 

networks:
  hazelcast-net:


    driver: bridge