spring.application.name=poc-distributed-systems

# Redis Cluster

#spring.data.redis.host=redis-1
#spring.data.redis.port=6379

#spring.redis.lettuce.pool.max-active=8
#spring.redis.lettuce.pool.max-idle=8
#spring.redis.lettuce.pool.min-idle=0
#spring.redis.lettuce.shutdown-timeout=100ms

#spring.data.redis.timeout=2000ms


# Profile
spring.profiles.active=external

# Hazelcast
hazelcast.network.port.auto.increment=false
hazelcast.network.port=5701
hazelcast.network.join.multicast.enabled=false
hazelcast.network.join.tcp-ip.enabled=true
hazelcast.servers=hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701