spring.application.name=poc-distributed-systems
spring.data.redis.host=localhost
spring.redis.cluster.nodes=redis-1:6379,redis-2:6379,redis-3:6379spring.profiles.active=docker

hazelcast.network.port.auto.increment=false
# node1
hazelcast.network.port=5701
hazelcast.network.public-address=127.0.0.1:5701
