spring.application.name=poc-distributed-systems
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.profiles.active=embedded

hazelcast.network.port.auto.increment=false
# node1
hazelcast.network.port=5701
hazelcast.network.public-address=127.0.0.1:5701

# node2
